---
title: "getting-started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{getting-started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(strimetrics)
library(tidyverse)
```

# Import data
```{r}
gm_raw <- read.csv("data/bran edited.txt", sep = "\t")
  metadata <- read.csv("data/metadata_20230414.csv")

  # Save raw data as a fragment class

  test_fragments <- peak_table_to_fragments(gm_raw,
                                            fragment_class = "bp_fragments",
                                            data_format = "genemapper5",
                                            dye_channel = "B",
                                            min_size_bp = 400)
```

# add metadata
```{r}
test_metadata <- add_metadata(
    fragments_list = test_fragments,
    metadata_data.frame = metadata,
    unique_id = "unique_id",
    plate_id = "plate_id",
    sample_group_id = "cell_line",
    metrics_baseline_control = "metrics_baseline_control_TF",
    repeat_positive_control_TF = "repeat_positive_control_TF",
    repeat_positive_control_length = "repeat_positive_control_length")

```

# Identify modal peaks and call repeats

```{r}
test_alleles <- find_alleles(
    fragments_list = test_metadata,
    number_of_peaks_to_return = 1,
    peak_region_size_gap_threshold = 6,
    peak_region_height_threshold_multiplier = 1)


  test_repeats <- call_repeats(
    fragments_list = test_alleles,
    repeat_algorithm = "simple",
    assay_size_without_repeat = 87,
    repeat_size = 3,
    repeat_length_correction = "none"
  )
```

# Calculate instability metrics

```{r}
test_metrics_grouped <- calculate_instability_metrics(
    fragments_list = test_repeats,
    grouped = TRUE,
    peak_threshold = 0.05,
    # note the lower lim should be a negative value
    window_around_main_peak = c(-40, 40),
    percentile_range = c(0.01, 0.05, seq(0.1, 0.9, 0.1), 0.95, 0.99),
    repeat_range = c( 1,2,3,4,seq(6,20,2)))
```


```{r}
test_metrics_grouped |>
    left_join(metadata) |>
    group_by(cell_line) |>
    filter(day >0) |>
    mutate(rel_gain = average_repeat_gain / median(average_repeat_gain[which(treatment == 0)])) |>
    ggplot(aes(as.factor(treatment), rel_gain, colour = as.factor(treatment))) +
    geom_boxplot(outlier.shape = NA) +
    geom_jitter() +
    facet_wrap(vars(fct_rev(genotype)))
  
  

```

